; ============================================================
; m1_sample_basic.asm — M1.5 driver (SPEC §20.1, sample_basic).
;
; Single-voice playback (voice 0) with optional looping. Polls
; CPUIO0 for host commands; supports STOP, RESET_TO_IPL, PING.
; No tick interrupt, no multi-voice, no ADSR computation
; (precomputed in m1_constants.inc).
;
; Per-project constants come from m1_constants.inc, generated by
; core::driver_build.
;
; ------------------------------------------------------------
; Mapper trick (same as m0_smoke.asm):
;   - lorom selects the LoROM mapper.
;   - org $008200 puts code at file offset $0200.
;   - base $0200 makes labels resolve to ARAM addresses.
;   - The host invokes asar with --no-title-check
;     --fix-checksum=off so no LoROM checksum bytes get injected.
;
; Driver bytes are extracted from the assembled image by
; core::driver_build. The four-byte sentinel `$de $ad $be $ef`
; immediately after the last instruction marks the driver's
; end; bytes from $0200 up to (but not including) the sentinel
; are the driver_code blob.
;
; Direct-page state:
;   $00 = dp_last_token  (last command_token observed; SEEDED from
;                          $F4 at init — see step 8.1 — so the IPL
;                          exec residual byte is not mistaken for a
;                          fresh command on the first main_loop poll)
;   $01 = dp_status_flags (current status_flags byte)
; ============================================================

incsrc "m1_constants.inc"

lorom
arch spc700

org $008200
base $0200

; ------------------------------------------------------------
; Entry — runs once at SPC700 boot, then falls into main_loop.
; ------------------------------------------------------------
driver_entry:
    ; 1. Mute amp + echo write disable while we set up DSP regs.
    mov $f2, #$6c                   ; FLG
    mov $f3, #$60

    ; 2. Clear KON / KOFF.
    mov $f2, #$4c
    mov $f3, #$00
    mov $f2, #$5c
    mov $f3, #$00

    ; 3. Master volumes.
    mov $f2, #$0c
    mov $f3, #master_voll
    mov $f2, #$1c
    mov $f3, #master_volr

    ; 4. Source directory page.
    mov $f2, #$5d                   ; DIR
    mov $f3, #src_dir_page

    ; 5. Echo parameters first; EON last so the FIR + ESA + EDL
    ;    are all set before echo writeback can begin.
    mov $f2, #$0d
    mov $f3, #echo_efb
    mov $f2, #$2c
    mov $f3, #echo_evoll
    mov $f2, #$3c
    mov $f3, #echo_evolr
    mov $f2, #$6d
    mov $f3, #echo_esa
    mov $f2, #$7d
    mov $f3, #echo_edl
    mov $f2, #$0f
    mov $f3, #echo_fir_0
    mov $f2, #$1f
    mov $f3, #echo_fir_1
    mov $f2, #$2f
    mov $f3, #echo_fir_2
    mov $f2, #$3f
    mov $f3, #echo_fir_3
    mov $f2, #$4f
    mov $f3, #echo_fir_4
    mov $f2, #$5f
    mov $f3, #echo_fir_5
    mov $f2, #$6f
    mov $f3, #echo_fir_6
    mov $f2, #$7f
    mov $f3, #echo_fir_7
    mov $f2, #$4d                   ; EON
    mov $f3, #echo_eon

    ; 6. Voice 0 configuration.
    mov $f2, #$00
    mov $f3, #voice0_voll
    mov $f2, #$01
    mov $f3, #voice0_volr
    mov $f2, #$02
    mov $f3, #voice0_pitchl
    mov $f2, #$03
    mov $f3, #voice0_pitchh
    mov $f2, #$04
    mov $f3, #voice0_srcn
    mov $f2, #$05
    mov $f3, #voice0_adsr1
    mov $f2, #$06
    mov $f3, #voice0_adsr2
    mov $f2, #$07
    mov $f3, #voice0_gain

    ; 7. FLG: unmute amp; ECEN bit per master_echo policy.
    mov $f2, #$6c
    mov $f3, #flg_running

    ; 8. Direct-page state. Note: dp_last_token gets seeded in 8.1
    ; from the live host port, not zero-initialised — the M2.0
    ; bootstrap fix.
    mov $01, #status_flags_initial

    ; 8.1 Seed dp_last_token from the current host-port value so any
    ; residual byte from IPL upload/exec (the kick byte sitting on
    ; CPUIO0 after the loader's "$2141 = $00 → exec" handshake) is
    ; not mistaken for a fresh host command on the first main_loop
    ; poll. Pre-M2.0 the driver wrote zero here and then read $F4 in
    ; main_loop; the .sfc IPL exec path leaves $F4 non-zero, so the
    ; first poll fired the invalid-command path, stomped $F5 with
    ; $EE, and tripped the loader's wait_driver_ready timeout. The
    ; .spc / oracle path is unaffected because spc_load_spc
    ; initialises $F4 from the embedded ARAM image (zero).
    ;
    ; Expected encoded bytes: E4 F4 C4 00 (asar picks the 2-byte
    ; direct-page form for $F4 since both source and dest are in
    ; DP).
    ;   E4 F4 = mov a, $f4 (load CPUIO0 host-port mirror)
    ;   C4 00 = mov $00, a (store into dp_last_token)
    ;
    ; The regression test in tests/m1_driver_bootstrap.rs locks the
    ; encoded bytes; if asar emits a different addressing form that
    ; still reads CPUIO0 and stores to dp $00, update the regression
    ; test accordingly.
    mov a, $f4
    mov $00, a

    ; 9. KON voice 0.
    mov $f2, #$4c
    mov $f3, #$01

    ; 10. Driver-ready signature on $F4..$F7.
    mov $f4, #$a5
    mov $f5, #$5a
    mov $f6, #$01                   ; driver_version (M1 = 1)
    mov $f7, $01                    ; status_flags

    ; Fall through.

; ------------------------------------------------------------
; Main loop — poll host_in_0 (= CPUIO0 = $F4) for token change.
; ------------------------------------------------------------
main_loop:
    mov a, $f4
    cmp a, $00
    beq main_loop
    mov $00, a                      ; always update; idle if same next time
    mov a, $f5                      ; command_code
    cmp a, #$01
    beq handle_stop
    cmp a, #$02
    beq handle_reset_to_ipl
    cmp a, #$7f
    beq handle_ping
    ; fall through: invalid command

reject_command:
    mov a, $01
    or a, #$08                      ; set error bit
    mov $01, a
    mov $f4, $00
    mov $f5, #$ee
    mov $f6, #$01
    mov $f7, $01
    bra main_loop

handle_stop:
    mov $f2, #$5c                   ; KOFF
    mov $f3, #$01
    mov a, $01
    and a, #$fe                     ; clear voice0_active
    or a, #$04                      ; set stopped
    mov $01, a
    mov $f4, $00
    mov $f5, #$81
    mov $f6, #$01
    mov $f7, $01
    bra main_loop

handle_ping:
    mov $f4, $00
    mov $f5, #$ff
    mov $f6, #$01
    mov $f7, $01
    bra main_loop

handle_reset_to_ipl:
    mov a, $01
    or a, #$10                      ; reset_to_ipl_pending
    mov $01, a
    mov $f4, $00
    mov $f5, #$82
    mov $f6, #$01
    mov $f7, $01
    mov $f2, #$5c                   ; KOFF voice 0
    mov $f3, #$01
    mov $f2, #$6c                   ; FLG mute + echo write disable
    mov $f3, #$60
    mov $f2, #$4d                   ; EON = 0
    mov $f3, #$00
    mov $f1, #$80                   ; CONTROL bit 7: map IPL ROM
    jmp $ffc0

driver_end:
    db $de, $ad, $be, $ef           ; sentinel — see file header
